apiVersion: batch/v1
kind: Job
metadata:
  name: blackjack-job
spec:
  template:
    spec:
      containers:
      - name: blackjack-job
        image: yash5090/blackjack:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
